title: AdminLTE v3.2 Documentation
version: v3.2
description: AdminLTE v3.2 Documentation

baseurl: /docs/3.2
url: https://adminlte.io

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

navigation:
  - title: Installation
    url: index.html
    icon: fa fa-microchip
  - title: Dependencies & Plugins
    url: dependencies.html
    icon: fa fa-handshake
  - title: Layout
    url: layout.html
    icon: fa fa-copy
  - title: Components
    icon: fa fa-th
    url: components
    subitems:
      - title: Main Header
        url: components/main-header.html
      - title: Main Sidebar
        url: components/main-sidebar.html
      - title: Control Sidebar
        url: components/control-sidebar.html
      - title: Card
        url: components/cards.html
      - title: Small-/ Info-Box
        url: components/boxes.html
      - title: Direct Chat
        url: components/direct-chat.html
      - title: Timeline
        url: components/timeline.html
      - title: Ribbons
        url: components/ribbons.html
      - title: Miscellaneous
        url: components/miscellaneous.html
      - title: Plugins
        url: components/plugins.html
  - title: JavaScript
    icon: fa fa-code
    url: javascript
    subitems:
      - title: Layout
        url: javascript/layout.html
      - title: Push Menu
        url: javascript/push-menu.html
      - title: Treeview
        url: javascript/treeview.html
      - title: Card Widget
        url: javascript/card-widget.html
      - title: CardRefresh
        url: javascript/card-refresh.html
      - title: Control Sidebar
        url: javascript/control-sidebar.html
      - title: Direct Chat
        url: javascript/direct-chat.html
      - title: Todo List
        url: javascript/todo-list.html
      - title: Toasts
        url: javascript/toasts.html
      - title: Sidebar Search
        url: javascript/sidebar-search.html
      - title: Expandable Tables
        url: javascript/expandable-tables.html
      - title: IFrame
        url: javascript/iframe.html
      - title: Navbar Search
        url: javascript/navbar-search.html
  - title: Browser Support
    url: browser-support.html
    icon: fab fa-chrome
  - title: Implementations
    url: implementations.html
    icon: fa fa-bookmark
  - title: Additional Styles
    url: additional-styles.html
    icon: fa fa-mortar-pestle
  - title: Upgrade Guide
    url: upgrade-guide.html
    icon: fa fa-hand-point-up
  - title: Contributing Guide
    url: how-to-contribute.html
    icon: fa fa-hands-helping
  - title: FAQ
    url: faq.html
    icon: fa fa-question-circle
  - title: License
    url: license.html
    icon: fa fa-file-contract
